/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// Tiling 常量和结构体 - kernel 和 host 共用
// 此文件只含纯 C/C++ 语法，不含 __aicore__、__gm__ 等 ASC 关键字

#pragma once

#include <cstdint>

// Tiling 常量（来自 DESIGN.md §2.1 和 §2.2）
constexpr uint32_t ELEM_ALIGN_FACTOR = 512;         // 多核切分对齐因子
constexpr uint32_t REPEAT_BYTES = 256;              // UB 切分对齐字节
constexpr uint32_t MIN_TILING_BITS_SIZE_PER_CORE = 32768;  // 每核最小处理 4KB
constexpr uint32_t DOUBLE_BUFFER_NUM = 2;           // Double Buffer 数量

// Tiling 数据结构 - 向核函数传递的运行时参数
struct AbsTilingData {
    uint32_t blockNum;          // 使用的核数
    uint32_t blockFormer;       // 每个核处理的基础元素数（对齐到 512）
    uint32_t blockTail;         // 最后一个核处理的尾部元素数
    
    uint32_t ubFormer;          // UB 单次处理元素数（对齐到 256B）
    uint32_t ubLoopOfFormerBlock;   // 非尾 block 的 UB 循环次数
    uint32_t ubTailOfFormerBlock;   // 非尾 block 的 UB 尾部元素数
    uint32_t ubLoopOfTailBlock;     // 尾 block 的 UB 循环次数
    uint32_t ubTailOfTailBlock;     // 尾 block 的 UB 尾部元素数
    
    uint32_t totalLength;       // 总元素数
    uint32_t dtypeSize;         // 数据类型大小（2 for half, 4 for float）
};