/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// Tiling 常量和结构体 - kernel 和 host 共用
// （kernel 侧不做 broadcast，由 host 预扩展后传入等长输入）

#pragma once

#include <cstdint>

constexpr uint32_t TILE_LENGTH = 4096;
constexpr uint32_t DOUBLE_BUFFER = 2;
constexpr uint32_t MAX_DIMS = 4;

struct GcdTilingData {
    uint32_t blockNum;
    uint64_t totalLength;
    uint64_t numPerCore;
    uint64_t tailNumLastCore;
};

// ===== Host-only 工具函数（kernel 侧不调用） =====

// 计算 broadcast 输出 shape
inline void ComputeBroadcastShape(
    const int32_t selfShape[MAX_DIMS],
    const int32_t otherShape[MAX_DIMS],
    int32_t outShape[MAX_DIMS])
{
    for (int32_t i = MAX_DIMS - 1; i >= 0; i--) {
        int32_t s = selfShape[i];
        int32_t o = otherShape[i];
        if (s == o) {
            outShape[i] = s;
        } else if (s == 1) {
            outShape[i] = o;
        } else if (o == 1) {
            outShape[i] = s;
        } else {
            outShape[i] = -1;  // caller 需校验
        }
    }
}

// 计算 strides（行主序）
inline void ComputeStrides(const int32_t shape[MAX_DIMS], int32_t strides[MAX_DIMS])
{
    strides[MAX_DIMS - 1] = 1;
    for (int32_t i = MAX_DIMS - 2; i >= 0; i--) {
        strides[i] = strides[i + 1] * shape[i + 1];
    }
}

// flat index from 4D indices
inline int32_t FlatIndex(const int32_t* strides, int32_t n4, int32_t n3, int32_t n2, int32_t n1)
{
    return n4 * strides[0] + n3 * strides[1] + n2 * strides[2] + n1 * strides[3];
}
