/*!
 * \file sync_batch_norm_backward_reduce_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __SYNCBATCHNORMBACKWARDREDUCE_TILING_KEY_H__
#define __SYNCBATCHNORMBACKWARDREDUCE_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_0 0
#define SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_1 1
#define SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_2 2

ASCENDC_TPL_ARGS_DECL(
    SyncBatchNormBackwardReduce,
    ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST, SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_0,
        SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_1, SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_2));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_0,
        SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_1, SYNCBATCHNORMBACKWARDREDUCE_TPL_SCH_MODE_2)));

#endif
