/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By AtomCode */

// ============================================================================
// Ascend C Kernel 实现 - Atanh 算子（纯 kernel，不含 host 代码）
// ============================================================================
//
// 数学公式: atanh(x) = 0.5 * ln((1 + x) / (1 - x)), 其中 |x| < 1
//
// 混合精度策略:
//   FP16 输入 → Cast(FP32) → 中间计算(FP32) → Cast(FP16) → FP16 输出
//   理由: (1+x)/(1-x) 在 x 接近 ±1 时分母趋近 0，FP16 精度不足以稳定计算
//
// 计算步骤（每个 Tile）:
//   1. Cast half → float (CAST_NONE, 无损升精度)
//   2. Adds(xFloat, 1.0f)        → tmp1 = x + 1
//   3. Muls(xFloat, -1.0f)       → xFloat = -x
//   4. Adds(xFloat, 1.0f)        → xFloat = 1 - x  (复用 xFloat 空间)
//   5. Div(tmp1, xFloat)          → ratio = (1+x)/(1-x)
//   6. Log(xFloat, tmp1)          → ln(ratio)     (复用 xFloat 空间)
//   7. Muls(xFloat, 0.5f)        → xFloat = 0.5 * ln(ratio)
//   8. Cast float → half (CAST_ROUND, 降精度舍入)
// ============================================================================

#include "kernel_operator.h"
#include "atanh_tiling.h"

using namespace AscendC;

class KernelAtanh {
public:
    __aicore__ inline KernelAtanh(TPipe* pipe)
    {
        pipe_ = pipe;
    }

    // 初始化: 设置 Global Tensor 和 UB Buffer
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y,
                                const __gm__ AtanhTilingData* tiling)
    {
        this->tiling = tiling;
        uint32_t blockIdx = GetBlockIdx();
        if (blockIdx < tiling->blockNum - 1) {
            total = tiling->numPerCore;
            tileNum = total / TILE_LENGTH;
            tailTileElementNum = TILE_LENGTH;
        } else {
            total = tiling->tailNumLastCore;
            tileNum = (total + (TILE_LENGTH - 1)) / TILE_LENGTH;
            tailTileElementNum = total - TILE_LENGTH * (tileNum - 1);
        }

        // 输入: half 类型 Global Tensor
        xGm.SetGlobalBuffer((__gm__ half*)x + blockIdx * tiling->numPerCore, total);
        // 输出: half 类型 Global Tensor
        zGm.SetGlobalBuffer((__gm__ half*)y + blockIdx * tiling->numPerCore, total);

        // 输入队列 (half): 1 个 queue, DOUBLE_BUFFER 个 buffer, 每个 TILE_LENGTH * sizeof(half) 字节
        pipe_->InitBuffer(inQueueX, DOUBLE_BUFFER, TILE_LENGTH * sizeof(half));

        // 输出队列 (half): 1 个 queue, DOUBLE_BUFFER 个 buffer, 每个 TILE_LENGTH * sizeof(half) 字节
        pipe_->InitBuffer(outQueueZ, DOUBLE_BUFFER, TILE_LENGTH * sizeof(half));

        // FP32 工作缓冲区 (纯计算, 不涉及 MTE 搬运)
        // workBuf1: xFloat / tmp1(1+x) / ratio
        // workBuf2: tmp2(1-x) / log
        pipe_->InitBuffer(workBuf1, TILE_LENGTH * sizeof(float));
        pipe_->InitBuffer(workBuf2, TILE_LENGTH * sizeof(float));
    }

    __aicore__ inline void Process()
    {
        uint32_t offset = 0;
        for (uint32_t i = 0; i < tileNum; i++) {
            uint32_t count = (i == tileNum - 1) ? tailTileElementNum : TILE_LENGTH;
            CopyIn(count, offset);
            Compute(count);
            CopyOut(count, offset);
            offset += count;
        }
    }

    // 从 GM 搬运数据到 UB (half), tileOffset 为当前 tile 的元素偏移量
    __aicore__ inline void CopyIn(uint32_t count, uint32_t tileOffset)
    {
        LocalTensor<half> xLocal = inQueueX.AllocTensor<half>();

        // 从 xGm 的 tileOffset 位置开始搬运
        DataCopyPad(xLocal, xGm[tileOffset],
            {1, static_cast<uint16_t>(count * sizeof(half)), 0, 0},
            {false, 0, 0, 0});

        inQueueX.EnQue(xLocal);
    }

    // 在 UB 中执行计算 (混合精度: half→float→half)
    __aicore__ inline void Compute(uint32_t count)
    {
        // 从输入队列取出 half 数据
        LocalTensor<half> xLocal = inQueueX.DeQue<half>();

        // 分配 FP32 工作 tensor
        LocalTensor<float> xFloat = workBuf1.Get<float>();
        LocalTensor<float> tmpFloat = workBuf2.Get<float>();

        // Step 1: half → float (CAST_NONE: 低→高精度, 无损)
        Cast<float, half>(xFloat, xLocal, RoundMode::CAST_NONE, count);

        // Step 2: tmpFloat = x + 1.0   (标量加法)
        Adds<float>(tmpFloat, xFloat, 1.0f, count);

        // Step 3: xFloat = -x          (标量乘法)
        Muls<float>(xFloat, xFloat, -1.0f, count);

        // Step 4: xFloat = 1 + (-x) = 1 - x  (标量加法)
        Adds<float>(xFloat, xFloat, 1.0f, count);

        // Step 5: tmpFloat = (1+x) / (1-x)   (除法)
        Div<float>(tmpFloat, tmpFloat, xFloat, count);

        // Step 6: xFloat = ln((1+x)/(1-x))   (自然对数)
        Log<float>(xFloat, tmpFloat, count);

        // Step 7: xFloat = 0.5 * ln(ratio)   (标量乘法)
        Muls<float>(xFloat, xFloat, 0.5f, count);

        // 分配输出队列 tensor (half)
        LocalTensor<half> zLocal = outQueueZ.AllocTensor<half>();

        // Step 8: float → half (CAST_ROUND: 高→低精度, 需要舍入)
        Cast<half, float>(zLocal, xFloat, RoundMode::CAST_ROUND, count);

        // 释放输入 tensor, 加入输出队列
        inQueueX.FreeTensor(xLocal);
        outQueueZ.EnQue<half>(zLocal);
    }

    // 将结果从 UB 搬运回 GM (half), tileOffset 为当前 tile 的元素偏移量
    __aicore__ inline void CopyOut(uint32_t count, uint32_t tileOffset)
    {
        LocalTensor<half> zLocal = outQueueZ.DeQue<half>();

        // 写入 zGm 的 tileOffset 位置
        DataCopyPad(zGm[tileOffset], zLocal,
            {1, static_cast<uint16_t>(count * sizeof(half)), 0, 0});

        outQueueZ.FreeTensor(zLocal);
    }

private:
    TPipe* pipe_;
    const __gm__ AtanhTilingData* tiling;

    // Global Tensor (half)
    GlobalTensor<half> xGm;
    GlobalTensor<half> zGm;

    // 输入/输出队列 (half, 通过 MTE 搬运)
    TQue<TPosition::VECIN, 1> inQueueX;
    TQue<TPosition::VECOUT, 1> outQueueZ;

    // 纯计算工作缓冲区 (FP32)
    TBuf<TPosition::VECCALC> workBuf1;
    TBuf<TPosition::VECCALC> workBuf2;

    uint32_t total;
    uint32_t tileNum;
    uint32_t tailTileElementNum;
};

// 核函数入口
extern "C" __global__ __vector__ void atanh_kernel(GM_ADDR x, GM_ADDR y, GM_ADDR tiling)
{
    TPipe pipe;
    KernelAtanh op(&pipe);
    op.Init(x, y, (__gm__ AtanhTilingData*)tiling);
    op.Process();
}
