/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// Tiling 常量和结构体 - kernel 和 host 共用
// 此文件只含纯 C/C++ 语法，不含 __aicore__、__gm__ 等 ASC 关键字

#pragma once

#include <cstdint>

// 单次搬运/处理的数据量（元素数）
// float16 (2B/元素) UB 占用约 16KB per buffer → 安全值 8192 元素
constexpr uint32_t TILE_LENGTH = 8192;
constexpr uint32_t DOUBLE_BUFFER = 2;
constexpr uint32_t GCD_MAX_ITER = 64;  // 欧几里得算法最大迭代次数 (保障 float16 全范围收敛)

// Tiling 数据结构 - 向核函数传递的运行时参数
struct GcdFloat16TilingData {
    uint32_t blockNum;
    uint64_t totalLength;        // broadcast 后的总元素数
    uint64_t numPerCore;
    uint64_t tailNumLastCore;
};
