/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#pragma once

#include <cstdint>

// [CONFIG] TILE_LENGTH: 单次搬运/处理的数据量（元素数）
// FP16（2字节/元素）: TILE_LENGTH = 4096 → 每个 buffer 8KB
// 三个 buffer = 输入x 8KB + 输入y 8KB + 输出z 8KB = 24KB，双缓冲 48KB
// UB (192/248KB) 充裕
constexpr uint32_t TILE_LENGTH = 4096;
constexpr uint32_t DOUBLE_BUFFER = 2;

// [CONFIG] Tiling 数据结构
struct GcdTilingData {
    uint32_t blockNum;          // 实际使用的 block 数
    uint64_t totalLength;       // broadcast 后的总元素数
    uint64_t numPerCore;        // 每个核处理的基础元素数
    uint64_t tailNumLastCore;   // 最后一个核处理的元素数
};
