/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// [CONFIG] Tiling 常量和结构体 - kernel 和 host 共用
// 此文件只含纯 C/C++ 语法，不含 __aicore__、__gm__ 等 ASC 关键字

#pragma once

#include <cstdint>

// [CONFIG] 单次搬运/处理的数据量（元素数），影响 UB 内存占用
// float32 计算 (4 bytes/el) + half 输入输出 (2 bytes/el)
// 设 TILE_LENGTH=4096 以控制 UB 总用量在 256KB 内
constexpr uint32_t TILE_LENGTH = 4096;
constexpr uint32_t DOUBLE_BUFFER = 2;

// [CONFIG] 欧几里得算法最大迭代次数
// float32 尾数 23bit，最坏情况约需 24 次迭代；设 24 留余量
constexpr uint32_t MAX_GCD_ITER = 24;

// Gcd Tiling 数据结构
struct GcdTilingData {
    uint32_t blockNum;
    uint64_t totalLength;
    uint64_t numPerCore;
    uint64_t tailNumLastCore;
};
